CREATE TABLE `CommunityConnection`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` BIGINT(8) NOT NULL,
	`E` DATE NOT NULL,
	`F` char(6) NOT NULL,
	`G` varchar(255) NOT NULL,
	`H` varchar(255) NOT NULL,
	`I` varchar(255) NOT NULL,
	`J` varchar(255) NOT NULL,
	`K` varchar(255) NOT NULL,
	`L` varchar(255),
	`M` varchar(255),
	`N` varchar(255) NOT NULL,
	`O` varchar(255) NOT NULL,
	`P` varchar(100),
	`Q` ENUM('Yes', 'No'),
	`R` ENUM('Yes', 'No'),
	`S` ENUM('Yes', 'No'),
	`T` ENUM('Yes', 'No'),
	`U` ENUM('Yes', 'No'),
	`V` ENUM('Yes', 'No'),
	`W` ENUM('Yes', 'No'),
	`X` ENUM('Yes', 'No'),
	`Y` ENUM('Yes', 'No'),
	`Z` ENUM('Yes', 'No'),
	`AA` ENUM('Yes', 'No'),
	`AB` ENUM('Yes', 'No'),
	`AC` ENUM('Yes', 'No'),
	`AD` ENUM('Yes', 'No'),
	`AE` ENUM('Yes', 'No'),
	`AF` ENUM('Yes', 'No'),
	`AG` varchar(255),
	`AH` varchar(255),
	`AI` DATE NOT NULL,
	`AJ` DATE,
	`AK` DATE,
	`AL` ENUM('yes', 'no') NOT NULL,
	`AM` ENUM('Yes', 'No'),
	`AN` ENUM('Yes', 'No'),
	`AO` ENUM('Yes', 'No'),
	`AP` ENUM('Yes', 'No'),
	`AQ` ENUM('Yes', 'No'),
	`AR` ENUM('Yes', 'No'),
	`AS` varchar(255) NOT NULL,
	`AT` ENUM('Yes', 'No'),
	`AU` varchar(255),
	`AV` varchar(255),
	`AW` varchar(255),
	`AX` varchar(255),
	`AY` varchar(255),
	`AZ` varchar(255),
	`BA` varchar(255),
	`BB` varchar(255),
	`BC` varchar(255),
	`BD` varchar(255),
	`BE` ENUM('Yes', 'No'),
	`BF` ENUM('Yes', 'No'),
	`BG` ENUM('Yes', 'No'),
	`BH` varchar(255),
	`BI` varchar(255),
	`BJ` ENUM('Yes', 'No'),
	`BK` varchar(255),
	`BL` varchar(255),
	`BM` ENUM('Yes', 'No'),
	`BN` varchar(255),
	`BO` varchar(255),
	`BP` varchar(255),

	PRIMARY KEY (`C`, `D`)
);

