CREATE TABLE `Employment`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` BIGINT(8) NOT NULL,
	`E` DATE NOT NULL,
	`F` char(6) NOT NULL,
	`G` ENUM('Yes', 'No') NOT NULL,
	`H` varchar(255),
	`I` varchar(255) NOT NULL,
	`J` varchar(255) NOT NULL,
	`K` varchar(255) NOT NULL,
	`L` varchar(255) NOT NULL,
	`M` DATE,
	`N` varchar(255) NOT NULL,
	`O` varchar(255) NOT NULL,
	`P` varchar(255),
	`Q` varchar(255),
	`R` varchar(255),
	`S` varchar(255),
	`T` varchar(255),
	`U` varchar(255),
	`V` DATE,
	`W` DATE,
	`X` varchar(255),
	`Y` varchar(25),
	`Z` varchar(255),
	`AA` varchar(255),
	`AB` varchar(255),
	`AC` varchar(255),
	`AD` ENUM('Yes', 'No'),
	`AE` ENUM('Yes', 'No'),
	`AF` ENUM('Yes', 'No'),
	`AG` ENUM('Yes', 'No'),
	`AH` ENUM('Yes', 'No'),
	`AI` ENUM('Yes', 'No'),
	`AJ` varchar(255),
	`AK` DATE,
	`AL` varchar(255),
	`AM` DATE,
	`AN` varchar(255),
	`AO` DATE,
	`AP` varchar(255),
	`AQ` DATE,
	`AR` varchar(255),
	`AS` DATE,
	`AT` ENUM('Yes', 'No'),
	`AU` ENUM('Yes', 'No'),
	`AV` varchar(40),
	`AW` varchar(40),
	`AX` varchar(40),
	`AY` varchar(40),
	`AZ` varchar(40),
	`BA` varchar(40),
	`BB` varchar(40),
	`BC` varchar(40),
	`BD` varchar(40),
	`BE` varchar(40),
	`BF` ENUM('Yes', 'No'),
	`BG` ENUM('Yes', 'No'),
	`BH` ENUM('Yes', 'No'),
	`BI` varchar(255),
	`BJ` varchar(255),
	`BK` ENUM('Yes', 'No'),
	`BL` varchar(255),
	`BM` varchar(255),
	`BN` ENUM('Yes', 'No'),
	`BO` int unsigned,
	`BP` int unsigned,
	`BQ` varchar(255),

	PRIMARY KEY (`C`, `D`)
);

