CREATE TABLE `InformationAndOrientation`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` BIGINT(8) NOT NULL,
	`E` varchar(255) NOT NULL,
	`F` char(8) NOT NULL,
	`G` varchar(255) NOT NULL,
	`H` varchar(255) NOT NULL,
	`I` varchar(255) NOT NULL,
	`J` varchar(255) NOT NULL,
	`K` varchar(255) NOT NULL,
	`L` varchar(255) NOT NULL,
	`M` varchar(255),
	`N` int unsigned,
	`O` int unsigned,
	`P` varchar(255),
	`Q` ENUM('Yes', 'No'),
	`R` ENUM('Yes', 'No'),
	`S` ENUM('Yes', 'No'),
	`T` ENUM('Yes', 'No'),
	`U` ENUM('Yes', 'No'),
	`V` ENUM('Yes', 'No'),
	`W` ENUM('Yes', 'No'),
	`X` ENUM('Yes', 'No'),
	`Y` ENUM('Yes', 'No'),
	`Z` ENUM('Yes', 'No'),
	`AA` ENUM('Yes', 'No'),
	`AB` ENUM('Yes', 'No'),
	`AC` ENUM('Yes', 'No'),
	`AD` ENUM('Yes', 'No'),
	`AE` ENUM('Yes', 'No'),
	`AF` ENUM('Yes', 'No'),
	`AG` ENUM('Yes', 'No'),
	`AH` ENUM('Yes', 'No'),
	`AI` ENUM('Yes', 'No'),
	`AJ` ENUM('Yes', 'No'),
	`AK` ENUM('Yes', 'No'),
	`AL` ENUM('Yes', 'No'),
	`AM` ENUM('Yes', 'No'),
	`AN` ENUM('Yes', 'No'),
	`AO` ENUM('Yes', 'No'),
	`AP` ENUM('Yes', 'No'),
	`AQ` ENUM('Yes', 'No'),
	`AR` ENUM('Yes', 'No'),
	`AS` ENUM('Yes', 'No'),
	`AT` ENUM('Yes', 'No'),
	`AU` ENUM('Yes', 'No'),
	`AV` ENUM('Yes', 'No'),
	`AW` ENUM('Yes', 'No'),
	`AX` ENUM('Yes', 'No'),
	`AY` ENUM('Yes', 'No'),
	`AZ` ENUM('Yes', 'No'),
	`BA` ENUM('Yes', 'No'),
	`BB` ENUM('Yes', 'No'),
	`BC` ENUM('Yes', 'No'),
	`BD` ENUM('Yes', 'No'),
	`BE` ENUM('Yes', 'No'),
	`BF` ENUM('Yes', 'No'),
	`BG` ENUM('Yes', 'No'),
	`BH` ENUM('Yes', 'No'),
	`BI` ENUM('Yes', 'No'),
	`BJ` ENUM('Yes', 'No'),
	`BK` ENUM('Yes', 'No'),
	`BL` ENUM('Yes', 'No'),
	`BM` ENUM('Yes', 'No'),
	`BN` ENUM('Yes', 'No'),
	`BO` ENUM('Yes', 'No'),
	`BP` ENUM('Yes', 'No'),
	`BQ` ENUM('Yes', 'No'),
	`BR` ENUM('Yes', 'No') NOT NULL,
	`BS` ENUM('Yes', 'No'),
	`BT` ENUM('Yes', 'No'),
	`BU` ENUM('Yes', 'No') NOT NULL,
	`BV` ENUM('Yes', 'No'),
	`BW` varchar(255),
	`BX` varchar(255),
	`BY` varchar(255),
	`BZ` varchar(255),
	`CA` varchar(255),
	`CB` varchar(255),
	`CC` varchar(255),
	`CD` varchar(255),
	`CE` varchar(255),
	`CF` varchar(255),
	`CG` ENUM('Yes', 'No'),
	`CH` ENUM('Yes', 'No'),
	`CI` ENUM('Yes', 'No'),
	`CJ` varchar(255),
	`CK` varchar(255),
	`CL` ENUM('Yes', 'No'),
	`CM` varchar(255),
	`CN` varchar(255),
	`CO` ENUM('Yes', 'No'),
	`CP` varchar(255) NOT NULL,
	`CQ` varchar(255),

	PRIMARY KEY (`C`, `D`)
);

