CREATE TABLE `LanguageTrainingSetup`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` varchar(255),
	`E` varchar(255) NOT NULL,
	`F` varchar(255) NOT NULL,
	`G` varchar(255) NOT NULL,
	`H` varchar(255),
	`I` TINYINT unsigned,
	`J` TINYINT unsigned,
	`K` int unsigned NOT NULL,
	`L` int unsigned NOT NULL,
	`M` varchar(100) NOT NULL,
	`N` ENUM('Yes', 'No') NOT NULL,
	`O` ENUM('Yes', 'No'),
	`P` ENUM('Yes', 'No'),
	`Q` ENUM('Yes', 'No'),
	`R` DATE NOT NULL,
	`S` DATE NOT NULL,
	`T` ENUM('Yes', 'No'),
	`U` ENUM('Yes', 'No'),
	`V` ENUM('Yes', 'No'),
	`W` ENUM('Yes', 'No'),
	`X` ENUM('Yes', 'No'),
	`Y` ENUM('Yes', 'No'),
	`Z` FLOAT NOT NULL,
	`AA` int unsigned NOT NULL,
	`AB` int unsigned,
	`AC` int unsigned,
	`AD` varchar(100) NOT NULL,
	`AE` ENUM('Yes', 'No') NOT NULL,
	`AF` ENUM('Yes', 'No'),
	`AG` ENUM('Yes', 'No'),
	`AH` ENUM('Yes', 'No'),
	`AI` ENUM('Yes', 'No'),
	`AJ` ENUM('Yes', 'No'),
	`AK` ENUM('Yes', 'No'),
	`AL` ENUM('Yes', 'No'),
	`AM` ENUM('Yes', 'No'),
	`AN` ENUM('Yes', 'No'),
	`AO` ENUM('Yes', 'No'),
	`AP` ENUM('Yes', 'No'),
	`AQ` ENUM('Yes', 'No'),
	`AR` ENUM('Yes', 'No'),
	`AS` ENUM('Yes', 'No'),
	`AT` ENUM('Yes', 'No') NOT NULL,
	`AU` ENUM('Yes', 'No'),
	`AV` ENUM('Yes', 'No'),
	`AW` varchar(255),
	`AX` int unsigned NOT NULL,
	`AY` varchar(255) NOT NULL,
	`AZ` varchar(255) NOT NULL,
	`BA` varchar(255),
	`BB` varchar(255),
	`BC` varchar(255) NOT NULL,
	`BD` varchar(255) NOT NULL,
	`BE` char(6) NOT NULL,
	`BF` varchar(20) NOT NULL,
	`BG` varchar(255),
	`BH` varchar(255) NOT NULL,
	`BI` varchar(8),
	`BJ` varchar(8),
	`BK` varchar(8),
	`BL` varchar(8),
	`BM` varchar(8),
	`BN` varchar(8),
	`BO` varchar(8),
	`BP` varchar(8),
	`BQ` varchar(8),
	`BR` varchar(8),
	`BS` varchar(8),
	`BT` varchar(8),
	`BU` varchar(8),
	`BV` varchar(8),
	`BW` varchar(8),
	`BX` varchar(8),
	`BY` varchar(8),
	`BZ` varchar(8),
	`CA` varchar(8),
	`CB` varchar(8),
	`CC` varchar(8),
	`CD` varchar(8),
	`CE` varchar(8),
	`CF` varchar(8),
	`CG` varchar(8),
	`CH` varchar(8),
	`CI` varchar(8),
	`CJ` varchar(8),
	`CK` varchar(8),
	`CL` varchar(8),
	`CM` varchar(8),
	`CN` varchar(8),
	`CO` varchar(8),
	`CP` varchar(8),
	`CQ` varchar(8),
	`CR` varchar(8),
	`CS` varchar(8),
	`CT` varchar(8),
	`CU` varchar(8),
	`CV` varchar(8),
	`CW` varchar(8),
	`CX` varchar(8),
	`CY` varchar(8),
	`CZ` varchar(8),
	`DA` varchar(8),
	`DB` varchar(8),
	`DC` varchar(8),
	`DD` varchar(8),
	`DE` varchar(8),
	`DF` varchar(8),
	`DG` varchar(8),
	`DH` varchar(8),
	`DI` varchar(8),
	`DJ` varchar(8),
	`DK` varchar(8),
	`DL` varchar(8),
	`DM` varchar(8),
	`DN` varchar(8),

	PRIMARY KEY (`C`, `D`)
);

