CREATE TABLE `LanguageTrainingEnrolment`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` BIGINT(8) NOT NULL,
	`E` varchar(255) NOT NULL,
	`F` char(6) NOT NULL,
	`G` varchar(255) NOT NULL,
	`H` varchar(255) NOT NULL,
	`I` varchar(255) NOT NULL,
	`J` ENUM('Yes', 'No') NOT NULL,
	`K` ENUM('Yes', 'No'),
	`L` varchar(40),
	`M` varchar(40),
	`N` varchar(40),
	`O` varchar(40),
	`P` varchar(40),
	`Q` varchar(40),
	`R` varchar(40),
	`S` varchar(40),
	`T` varchar(40),
	`U` varchar(40),
	`V` ENUM('Yes', 'No'),
	`W` ENUM('Yes', 'No'),
	`X` ENUM('Yes', 'No'),
	`Y` varchar(255),
	`Z` varchar(255),
	`AA` varchar(255),
	`AB` varchar(255),
	`AC` varchar(255),
	`AD` ENUM('Yes', 'No'),
	`AE` varchar(255),

	PRIMARY KEY (`C`, `D`)
);

