CREATE TABLE `LanguageTrainingExit`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` BIGINT(8) NOT NULL,
	`E` DATE NOT NULL,
	`F` varchar(255) NOT NULL,
	`G` varchar(255) NOT NULL,
	`H` DATE,
	`I` varchar(25),
	`J` varchar(25),
	`K` varchar(25),
	`L` varchar(25),
	`M` varchar(25),
	`N` ENUM('Yes', 'No') NOT NULL,
	`O` varchar(25),
	`P` varchar(25),
	`Q` ENUM('Yes', 'No') NOT NULL,
	`R` ENUM('Yes', 'No'),
	`S` varchar(40),
	`T` varchar(40),
	`U` varchar(40),
	`V` varchar(40),
	`W` varchar(40),
	`X` varchar(40),
	`Y` varchar(40),
	`Z` varchar(40),
	`AA` varchar(40),
	`AB` varchar(40),
	`AC` ENUM('Yes', 'No'),
	`AD` ENUM('Yes', 'No'),
	`AE` ENUM('Yes', 'No'),
	`AF` varchar(255),
	`AG` varchar(255),
	`AH` ENUM('Yes', 'No'),
	`AI` varchar(255),
	`AJ` varchar(255),
	`AK` ENUM('Yes', 'No'),
	`AL` varchar(255),

	PRIMARY KEY (`C`, `D`)
);

