CREATE TABLE `NeedAssessmentReferrals`(
	`A` varchar(255),
	`B` BIGINT(8),
	`C` varchar(255) NOT NULL,
	`D` BIGINT(8) NOT NULL,
	`E` DATE NOT NULL,
	`F` char(6) NOT NULL,
	`G` DATE NOT NULL,
	`H` varchar(255) NOT NULL,
	`I` varchar(255) NOT NULL,
	`J` varchar(255) NOT NULL,
	`K` varchar(255) NOT NULL,
	`L` ENUM('Yes', 'No'),
	`M` ENUM('Yes', 'No'),
	`N` ENUM('Yes', 'No'),
	`O` ENUM('Yes', 'No'),
	`P` ENUM('Yes', 'No'),
	`Q` ENUM('Yes', 'No'),
	`R` ENUM('Yes', 'No'),
	`S` ENUM('Yes', 'No'),
	`T` ENUM('Yes', 'No'),
	`U` ENUM('Yes', 'No'),
	`V` ENUM('Yes', 'No'),
	`W` ENUM('Yes', 'No'),
	`X` ENUM('Yes', 'No'),
	`Y` ENUM('Yes', 'No'),
	`Z` ENUM('Yes', 'No'),
	`AA` ENUM('Yes', 'No'),
	`AB` ENUM('Yes', 'No'),
	`AC` ENUM('Yes', 'No'),
	`AD` varchar(255),
	`AE` ENUM('Yes', 'No'),
	`AF` ENUM('Yes', 'No'),
	`AG` varchar(255),
	`AH` ENUM('Yes', 'No'),
	`AI` ENUM('Yes', 'No'),
	`AJ` varchar(255),
	`AK` varchar(255),
	`AL` varchar(255),
	`AM` varchar(255),
	`AN` ENUM('Yes', 'No', 'Unknown/Not sure') NOT NULL,
	`AO` ENUM('Yes', 'No') NOT NULL,
	`AP` varchar(255),
	`AQ` ENUM('Yes', 'No'),
	`AR` ENUM('Yes', 'No'),
	`AS` ENUM('Yes', 'No'),
	`AT` ENUM('Yes', 'No'),
	`AU` ENUM('Yes', 'No'),
	`AV` ENUM('Yes', 'No') NOT NULL,
	`AW` ENUM('Yes', 'No'),
	`AX` ENUM('Yes', 'No'),
	`AY` ENUM('Yes', 'No'),
	`AZ` ENUM('Yes', 'No'),
	`BA` ENUM('Yes', 'No'),
	`BB` ENUM('Yes', 'No'),
	`BC` ENUM('Yes', 'No'),
	`BD` ENUM('Yes', 'No'),
	`BE` ENUM('Yes', 'No'),
	`BF` ENUM('Yes', 'No'),
	`BG` ENUM('Yes', 'No'),
	`BH` ENUM('Yes', 'No'),
	`BI` ENUM('Yes', 'No'),
	`BJ` ENUM('Yes', 'No'),
	`BK` ENUM('Yes', 'No'),
	`BL` ENUM('Yes', 'No'),
	`BM` ENUM('Yes', 'No'),
	`BN` ENUM('Yes', 'No'),
	`BO` ENUM('Yes', 'No'),
	`BP` ENUM('Yes', 'No'),
	`BQ` ENUM('Yes', 'No') NOT NULL,
	`BR` ENUM('Yes', 'No'),
	`BS` varchar(40),
	`BT` varchar(40),
	`BU` varchar(40),
	`BV` varchar(40),
	`BW` varchar(40),
	`BX` varchar(40),
	`BY` varchar(40),
	`BZ` varchar(40),
	`CA` varchar(40),
	`CB` varchar(40),
	`CC` ENUM('Yes', 'No'),
	`CD` ENUM('Yes', 'No'),
	`CE` ENUM('Yes', 'No'),
	`CF` varchar(255),
	`CG` varchar(255),
	`CH` ENUM('Yes', 'No'),
	`CI` varchar(255),
	`CJ` varchar(255),
	`CK` ENUM('Yes', 'No'),
	`CL` ENUM('Yes', 'No') NOT NULL,
	`CM` DATE NOT NULL,
	`CN` varchar(255),

	PRIMARY KEY (`C`, `D`)
);

